### PR TITLE
Run rubocop

### PR DESCRIPTION
**Pull request by roschaefer**
Wait until #22 is being merged. From the commit message:

    OK, the diff is hard to understand, here's what I did:
    1. Update the supported ruby version in `threema.gemspec` to `> =2.4`
    2. Remove trailing comma in literal cop from `rubocop_todo.yml`, as it was outdated and not supported anymore.
    3. Run `bundle exec rubocop -A`
    4. Fix one cop manually by adding`_` underscore to unused variable in `lib/threema/receive/image.rb`
    5. For the remaining cops, I decided to do:
      * `rm .rubocop_todo.yml`
      * `bundle exec rubocop --auto-gen-config`
      To recreate the config file

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Hi @roschaefer - this PR is marked as a draft. Are you planning to add more changes? Personally I liked the aligned hash parameters. Better readability IMHO but I'm good with changing it to community defaults.

**Comment by roschaefer** [comment]
@thorsteneckel the only reason why this is marked as draft is that I wanted to rebase this PR on `origin/master` once #22 is merged. It's not so easy with forks to have:
```
master <-- PR1 <-- PR2
```

I sometimes do that in order to make it easier for the maintainer (you) to review my PRs.

**Comment by roschaefer** [comment]
Here you go.

**Comment by thorsteneckel** [comment]
Would you mind resolving the conflict? Happily merging afterwards.

**Comment by roschaefer** [comment]
@thorsteneckel do you know what needs to be done to enable reviews?

swappy-20210301_093402

**Comment by thorsteneckel** [comment]
Merged and invited you to become a collaborator on this repository 💌

**Pull request merged**
